# Generated by Django 4.1 on 2022-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telephone'),
        ),
    ]
